export const ADD_ACCOUNT = "ADD_ACCOUNT";
export const ACCOUNTS_LOADING = "ACCOUNTS_LOADING";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";
export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const GET_TRANSACTIONS = "GET_TRANSACTIONS";
export const TRANSACTIONS_LOADING = "TRANSACTIONS_LOADING";
